### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by aelishRollo** [noahbaron91/visitarandomwebsite#1]
I was excited to use your site but cannot because it's down. Not that your server is returning an error, rather that it does not seem that a site is deployed at your URL currently

**Comment by longergrass** [comment]
Hi @aelishRollo! That's what is expected right now.

I just made the repository public when I initially created it. I'm currently in the process of crawling random millions of URLs so give it a few more days and it should be live! 

I appreciate the heads up though
