### ISSUE TITLE
Site owners should be able to exclude their sites

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [noahbaron91/visitarandomwebsite#23]
Some may not want their site indexed. Is there a way for them to opt-out? Does the crawlers respect `robots.txt`? If so what should they include to opt out?

**Comment by longergrass** [comment]
You can block the ```VisitARandomWebsite``` user-agent in your robots.txt for domains you don't want indexed.
Eg:
```
User-agent: VisitARandomWebsite
Disallow: /
```
