### ISSUE TITLE
Animation and UX

### ISSUE THREAD

**Issue by ozdevi** [noahbaron91/visitarandomwebsite#28]
I was looking for a while a **stumbleupon** alternative and found this website. The issue with the application is animation part. For onboarding a user, it is quite nice but it is getting boring after use for get couple of random website. 

Entire website functionality ( get a random link ) could move into header section and an next random website can be managed in a iframe

**Comment by longergrass** [comment]
![image](https://github.com/user-attachments/assets/5d65675a-e53a-43a3-9cf4-232e6c82e215)
I have an instant mode here that automatically redirects you.

The <iframe> idea sounds interesting although some websites prohibit themselves from being loaded inside iframes. 

It's worth looking into though.
