### ISSUE TITLE
Some comments and thoughts

### ISSUE THREAD

**Issue by Diwannist** [noahbaron91/visitarandomwebsite#32]
24 websites

7 websites didn't resolve at all

tumblr appeared 3 times (all pages were not found)

Wouldn't it be better if all domains had an equal chance of showing up?

Also, shouldn't HTTP error 500, sites that don't support HTTPS, DNS addresses that could not be found be filtered from the random website generator?

![1](https://github.com/user-attachments/assets/5da73019-d566-475f-8243-70783624ee43)

**Comment by longergrass** [comment]
Hi, I'm not currently working on this project. I'm willing to accept PRs or you can fork. Thanks :)
